ModuleName    = "github.com/repository/package"
ServerDir     = "app/server"
UsecaseDir    = "usecase"
DomainRepoDir = "domain/repository"
EntityDir     = "domain/entity"
InfraModelDir = "infra/model"
RepoDir       = "infra/repository"
ProtoDir      = "api/proto"
PbGoDir       = "api"
MigrationDir  = "migrate"
ManifestsDir  = "manifests"
ImageRegistry = "example.io/company"
