// Code generated by github.com/izumin5210/grapi. DO NOT EDIT.

package server

import (
	"context"

	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"google.golang.org/grpc"

	api_pb "github.com/volare-backend/monolith/api"
)

// RegisterWithServer implements grapiserver.Server.RegisterWithServer.
func (s *sampleServiceServerImpl) RegisterWithServer(grpcSvr *grpc.Server) {
	api_pb.RegisterSampleServiceServer(grpcSvr, s)
}

// RegisterWithHandler implements grapiserver.Server.RegisterWithHandler.
func (s *sampleServiceServerImpl) RegisterWithHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return api_pb.RegisterSampleServiceHandler(ctx, mux, conn)
}
