// Code generated by roche

package repository

import "backend/domain/entity"

type IEnterpriseRepository interface {
	GetList() ([]*entity.Enterprise, error)
	GetByID(id int64) (*entity.Enterprise, error)
	Create(enterprise *entity.Enterprise) (*entity.Enterprise, error)
	Update(id string, enterprise *entity.Enterprise) (*entity.Enterprise, error)
	Delete(id int64) error
}
