// Code generated by roche

package repository

type IEnterprise interface {
	GetList() ([]Enterprise, error)
	GetByID(id int64) (*Enterprise, error)
	Create(id string, name string, imageUrl string, description string, homepage string) (*Enterprise, error)
	Update(id string, name string, imageUrl string, description string, homepage string, id int64) (*Enterprise, error)
	Delete() error
}
