// Code generated by roche

package repository

type IEnterpriseRepository interface {
	GetList() ([]*entity.Enterprise, error)
	GetByID(id int64) (*entity.Enterprise, error)
	Create(*entity.Enterprise) (*entity.Enterprise, error)
	Update(int64, *entity.Enterprise) (*entity.Enterprise, error)
	Delete(int64) error
}
