// Code generated by roche

package repository

type ISampleRepository interface {
	GetList() ([]*entity.Sample, error)
	GetByID(id int64) (*entity.Sample, error)
	Create(*entity.Sample) (*entity.Sample, error)
	Update(int64, *entity.Sample) (*entity.Sample, error)
	Delete(int64) error
}
