CREATE TABLE IF NOT EXISTS `sample` (
  `hoge` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `age` BIGINT NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);