// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.17.0
// source: enterprise.proto

package enterprise

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Enterprise struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImageUrl    string `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Homepage    string `protobuf:"bytes,5,opt,name=homepage,proto3" json:"homepage,omitempty"`
}

func (x *Enterprise) Reset() {
	*x = Enterprise{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enterprise_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Enterprise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enterprise) ProtoMessage() {}

func (x *Enterprise) ProtoReflect() protoreflect.Message {
	mi := &file_enterprise_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enterprise.ProtoReflect.Descriptor instead.
func (*Enterprise) Descriptor() ([]byte, []int) {
	return file_enterprise_proto_rawDescGZIP(), []int{0}
}

func (x *Enterprise) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Enterprise) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Enterprise) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Enterprise) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Enterprise) GetHomepage() string {
	if x != nil {
		return x.Homepage
	}
	return ""
}

type CreateEnterpriseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enterprise *Enterprise `protobuf:"bytes,1,opt,name=enterprise,proto3" json:"enterprise,omitempty"`
}

func (x *CreateEnterpriseRequest) Reset() {
	*x = CreateEnterpriseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enterprise_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEnterpriseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEnterpriseRequest) ProtoMessage() {}

func (x *CreateEnterpriseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enterprise_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEnterpriseRequest.ProtoReflect.Descriptor instead.
func (*CreateEnterpriseRequest) Descriptor() ([]byte, []int) {
	return file_enterprise_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEnterpriseRequest) GetEnterprise() *Enterprise {
	if x != nil {
		return x.Enterprise
	}
	return nil
}

type CreateEnterpriseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateEnterpriseResponse) Reset() {
	*x = CreateEnterpriseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enterprise_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEnterpriseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEnterpriseResponse) ProtoMessage() {}

func (x *CreateEnterpriseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enterprise_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEnterpriseResponse.ProtoReflect.Descriptor instead.
func (*CreateEnterpriseResponse) Descriptor() ([]byte, []int) {
	return file_enterprise_proto_rawDescGZIP(), []int{2}
}

type GetEnterpriseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetEnterpriseRequest) Reset() {
	*x = GetEnterpriseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enterprise_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEnterpriseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnterpriseRequest) ProtoMessage() {}

func (x *GetEnterpriseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enterprise_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnterpriseRequest.ProtoReflect.Descriptor instead.
func (*GetEnterpriseRequest) Descriptor() ([]byte, []int) {
	return file_enterprise_proto_rawDescGZIP(), []int{3}
}

func (x *GetEnterpriseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetEnterpriseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enterprise *Enterprise `protobuf:"bytes,1,opt,name=enterprise,proto3" json:"enterprise,omitempty"`
}

func (x *GetEnterpriseResponse) Reset() {
	*x = GetEnterpriseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enterprise_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEnterpriseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnterpriseResponse) ProtoMessage() {}

func (x *GetEnterpriseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enterprise_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnterpriseResponse.ProtoReflect.Descriptor instead.
func (*GetEnterpriseResponse) Descriptor() ([]byte, []int) {
	return file_enterprise_proto_rawDescGZIP(), []int{4}
}

func (x *GetEnterpriseResponse) GetEnterprise() *Enterprise {
	if x != nil {
		return x.Enterprise
	}
	return nil
}

type UpdateEnterpriseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enterprise *Enterprise `protobuf:"bytes,1,opt,name=enterprise,proto3" json:"enterprise,omitempty"`
}

func (x *UpdateEnterpriseRequest) Reset() {
	*x = UpdateEnterpriseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enterprise_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateEnterpriseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEnterpriseRequest) ProtoMessage() {}

func (x *UpdateEnterpriseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enterprise_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEnterpriseRequest.ProtoReflect.Descriptor instead.
func (*UpdateEnterpriseRequest) Descriptor() ([]byte, []int) {
	return file_enterprise_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateEnterpriseRequest) GetEnterprise() *Enterprise {
	if x != nil {
		return x.Enterprise
	}
	return nil
}

type UpdateEnterpriseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateEnterpriseResponse) Reset() {
	*x = UpdateEnterpriseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enterprise_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateEnterpriseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEnterpriseResponse) ProtoMessage() {}

func (x *UpdateEnterpriseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enterprise_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEnterpriseResponse.ProtoReflect.Descriptor instead.
func (*UpdateEnterpriseResponse) Descriptor() ([]byte, []int) {
	return file_enterprise_proto_rawDescGZIP(), []int{6}
}

type DeleteEnterpriseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteEnterpriseRequest) Reset() {
	*x = DeleteEnterpriseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enterprise_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEnterpriseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEnterpriseRequest) ProtoMessage() {}

func (x *DeleteEnterpriseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enterprise_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEnterpriseRequest.ProtoReflect.Descriptor instead.
func (*DeleteEnterpriseRequest) Descriptor() ([]byte, []int) {
	return file_enterprise_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteEnterpriseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteEnterpriseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteEnterpriseResponse) Reset() {
	*x = DeleteEnterpriseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enterprise_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEnterpriseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEnterpriseResponse) ProtoMessage() {}

func (x *DeleteEnterpriseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enterprise_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEnterpriseResponse.ProtoReflect.Descriptor instead.
func (*DeleteEnterpriseResponse) Descriptor() ([]byte, []int) {
	return file_enterprise_proto_rawDescGZIP(), []int{8}
}

type ListAllEnterprisesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAllEnterprisesRequest) Reset() {
	*x = ListAllEnterprisesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enterprise_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAllEnterprisesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllEnterprisesRequest) ProtoMessage() {}

func (x *ListAllEnterprisesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enterprise_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllEnterprisesRequest.ProtoReflect.Descriptor instead.
func (*ListAllEnterprisesRequest) Descriptor() ([]byte, []int) {
	return file_enterprise_proto_rawDescGZIP(), []int{9}
}

type ListAllEnterprisesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enterprise []*Enterprise `protobuf:"bytes,1,rep,name=enterprise,proto3" json:"enterprise,omitempty"`
}

func (x *ListAllEnterprisesResponse) Reset() {
	*x = ListAllEnterprisesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enterprise_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAllEnterprisesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllEnterprisesResponse) ProtoMessage() {}

func (x *ListAllEnterprisesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enterprise_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllEnterprisesResponse.ProtoReflect.Descriptor instead.
func (*ListAllEnterprisesResponse) Descriptor() ([]byte, []int) {
	return file_enterprise_proto_rawDescGZIP(), []int{10}
}

func (x *ListAllEnterprisesResponse) GetEnterprise() []*Enterprise {
	if x != nil {
		return x.Enterprise
	}
	return nil
}

var File_enterprise_proto protoreflect.FileDescriptor

var file_enterprise_proto_rawDesc = []byte{
	0x0a, 0x10, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x1b, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8b, 0x01, 0x0a, 0x0a, 0x45, 0x6e, 0x74, 0x65, 0x72,
	0x70, 0x72, 0x69, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x6d, 0x65,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x6d, 0x65,
	0x70, 0x61, 0x67, 0x65, 0x22, 0x4e, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e,
	0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x33, 0x0a, 0x0a, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x45, 0x6e,
	0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x52, 0x0a, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70,
	0x72, 0x69, 0x73, 0x65, 0x22, 0x1a, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e,
	0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x26, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4c, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x45,
	0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x33, 0x0a, 0x0a, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x45, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x52, 0x0a, 0x65, 0x6e, 0x74, 0x65,
	0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x22, 0x4e, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x45, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x33, 0x0a, 0x0a, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x45, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x52, 0x0a, 0x65, 0x6e, 0x74, 0x65,
	0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x22, 0x1a, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x45, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x29, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x65,
	0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1a, 0x0a,
	0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1b, 0x0a, 0x19, 0x4c, 0x69, 0x73,
	0x74, 0x41, 0x6c, 0x6c, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x51, 0x0a, 0x1a, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c,
	0x6c, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x0a, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x52, 0x0a, 0x65,
	0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x32, 0xcf, 0x04, 0x0a, 0x11, 0x45, 0x6e,
	0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x76, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72,
	0x69, 0x73, 0x65, 0x12, 0x20, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17,
	0x22, 0x12, 0x2f, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x2f, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x3a, 0x01, 0x2a, 0x12, 0x67, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x45, 0x6e,
	0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x12, 0x1d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x11, 0x12,
	0x0f, 0x2f, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x2f, 0x67, 0x65, 0x74,
	0x12, 0x76, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x70,
	0x72, 0x69, 0x73, 0x65, 0x12, 0x20, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x17, 0x1a, 0x12, 0x2f, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x2f, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x3a, 0x01, 0x2a, 0x12, 0x68, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x12, 0x20, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6e, 0x74,
	0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x2a, 0x12,
	0x2f, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x2f, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x12, 0x77, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x45, 0x6e, 0x74,
	0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x73, 0x12, 0x22, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x70,
	0x72, 0x69, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x45, 0x6e,
	0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x12, 0x10, 0x2f, 0x65, 0x6e, 0x74, 0x65,
	0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x16, 0x5a, 0x14, 0x2e,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72,
	0x69, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_enterprise_proto_rawDescOnce sync.Once
	file_enterprise_proto_rawDescData = file_enterprise_proto_rawDesc
)

func file_enterprise_proto_rawDescGZIP() []byte {
	file_enterprise_proto_rawDescOnce.Do(func() {
		file_enterprise_proto_rawDescData = protoimpl.X.CompressGZIP(file_enterprise_proto_rawDescData)
	})
	return file_enterprise_proto_rawDescData
}

var file_enterprise_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_enterprise_proto_goTypes = []interface{}{
	(*Enterprise)(nil),                 // 0: service.Enterprise
	(*CreateEnterpriseRequest)(nil),    // 1: service.CreateEnterpriseRequest
	(*CreateEnterpriseResponse)(nil),   // 2: service.CreateEnterpriseResponse
	(*GetEnterpriseRequest)(nil),       // 3: service.GetEnterpriseRequest
	(*GetEnterpriseResponse)(nil),      // 4: service.GetEnterpriseResponse
	(*UpdateEnterpriseRequest)(nil),    // 5: service.UpdateEnterpriseRequest
	(*UpdateEnterpriseResponse)(nil),   // 6: service.UpdateEnterpriseResponse
	(*DeleteEnterpriseRequest)(nil),    // 7: service.DeleteEnterpriseRequest
	(*DeleteEnterpriseResponse)(nil),   // 8: service.DeleteEnterpriseResponse
	(*ListAllEnterprisesRequest)(nil),  // 9: service.ListAllEnterprisesRequest
	(*ListAllEnterprisesResponse)(nil), // 10: service.ListAllEnterprisesResponse
	(*emptypb.Empty)(nil),              // 11: google.protobuf.Empty
}
var file_enterprise_proto_depIdxs = []int32{
	0,  // 0: service.CreateEnterpriseRequest.enterprise:type_name -> service.Enterprise
	0,  // 1: service.GetEnterpriseResponse.enterprise:type_name -> service.Enterprise
	0,  // 2: service.UpdateEnterpriseRequest.enterprise:type_name -> service.Enterprise
	0,  // 3: service.ListAllEnterprisesResponse.enterprise:type_name -> service.Enterprise
	1,  // 4: service.EnterpriseService.CreateEnterprise:input_type -> service.CreateEnterpriseRequest
	3,  // 5: service.EnterpriseService.GetEnterprise:input_type -> service.GetEnterpriseRequest
	5,  // 6: service.EnterpriseService.UpdateEnterprise:input_type -> service.UpdateEnterpriseRequest
	7,  // 7: service.EnterpriseService.DeleteEnterprise:input_type -> service.DeleteEnterpriseRequest
	9,  // 8: service.EnterpriseService.ListAllEnterprises:input_type -> service.ListAllEnterprisesRequest
	2,  // 9: service.EnterpriseService.CreateEnterprise:output_type -> service.CreateEnterpriseResponse
	4,  // 10: service.EnterpriseService.GetEnterprise:output_type -> service.GetEnterpriseResponse
	6,  // 11: service.EnterpriseService.UpdateEnterprise:output_type -> service.UpdateEnterpriseResponse
	11, // 12: service.EnterpriseService.DeleteEnterprise:output_type -> google.protobuf.Empty
	10, // 13: service.EnterpriseService.ListAllEnterprises:output_type -> service.ListAllEnterprisesResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_enterprise_proto_init() }
func file_enterprise_proto_init() {
	if File_enterprise_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_enterprise_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Enterprise); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_enterprise_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEnterpriseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_enterprise_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEnterpriseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_enterprise_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEnterpriseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_enterprise_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEnterpriseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_enterprise_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateEnterpriseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_enterprise_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateEnterpriseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_enterprise_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteEnterpriseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_enterprise_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteEnterpriseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_enterprise_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAllEnterprisesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_enterprise_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAllEnterprisesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enterprise_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_enterprise_proto_goTypes,
		DependencyIndexes: file_enterprise_proto_depIdxs,
		MessageInfos:      file_enterprise_proto_msgTypes,
	}.Build()
	File_enterprise_proto = out.File
	file_enterprise_proto_rawDesc = nil
	file_enterprise_proto_goTypes = nil
	file_enterprise_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EnterpriseServiceClient is the client API for EnterpriseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EnterpriseServiceClient interface {
	CreateEnterprise(ctx context.Context, in *CreateEnterpriseRequest, opts ...grpc.CallOption) (*CreateEnterpriseResponse, error)
	GetEnterprise(ctx context.Context, in *GetEnterpriseRequest, opts ...grpc.CallOption) (*GetEnterpriseResponse, error)
	UpdateEnterprise(ctx context.Context, in *UpdateEnterpriseRequest, opts ...grpc.CallOption) (*UpdateEnterpriseResponse, error)
	DeleteEnterprise(ctx context.Context, in *DeleteEnterpriseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListAllEnterprises(ctx context.Context, in *ListAllEnterprisesRequest, opts ...grpc.CallOption) (*ListAllEnterprisesResponse, error)
}

type enterpriseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnterpriseServiceClient(cc grpc.ClientConnInterface) EnterpriseServiceClient {
	return &enterpriseServiceClient{cc}
}

func (c *enterpriseServiceClient) CreateEnterprise(ctx context.Context, in *CreateEnterpriseRequest, opts ...grpc.CallOption) (*CreateEnterpriseResponse, error) {
	out := new(CreateEnterpriseResponse)
	err := c.cc.Invoke(ctx, "/service.EnterpriseService/CreateEnterprise", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enterpriseServiceClient) GetEnterprise(ctx context.Context, in *GetEnterpriseRequest, opts ...grpc.CallOption) (*GetEnterpriseResponse, error) {
	out := new(GetEnterpriseResponse)
	err := c.cc.Invoke(ctx, "/service.EnterpriseService/GetEnterprise", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enterpriseServiceClient) UpdateEnterprise(ctx context.Context, in *UpdateEnterpriseRequest, opts ...grpc.CallOption) (*UpdateEnterpriseResponse, error) {
	out := new(UpdateEnterpriseResponse)
	err := c.cc.Invoke(ctx, "/service.EnterpriseService/UpdateEnterprise", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enterpriseServiceClient) DeleteEnterprise(ctx context.Context, in *DeleteEnterpriseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/service.EnterpriseService/DeleteEnterprise", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enterpriseServiceClient) ListAllEnterprises(ctx context.Context, in *ListAllEnterprisesRequest, opts ...grpc.CallOption) (*ListAllEnterprisesResponse, error) {
	out := new(ListAllEnterprisesResponse)
	err := c.cc.Invoke(ctx, "/service.EnterpriseService/ListAllEnterprises", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnterpriseServiceServer is the server API for EnterpriseService service.
type EnterpriseServiceServer interface {
	CreateEnterprise(context.Context, *CreateEnterpriseRequest) (*CreateEnterpriseResponse, error)
	GetEnterprise(context.Context, *GetEnterpriseRequest) (*GetEnterpriseResponse, error)
	UpdateEnterprise(context.Context, *UpdateEnterpriseRequest) (*UpdateEnterpriseResponse, error)
	DeleteEnterprise(context.Context, *DeleteEnterpriseRequest) (*emptypb.Empty, error)
	ListAllEnterprises(context.Context, *ListAllEnterprisesRequest) (*ListAllEnterprisesResponse, error)
}

// UnimplementedEnterpriseServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEnterpriseServiceServer struct {
}

func (*UnimplementedEnterpriseServiceServer) CreateEnterprise(context.Context, *CreateEnterpriseRequest) (*CreateEnterpriseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEnterprise not implemented")
}
func (*UnimplementedEnterpriseServiceServer) GetEnterprise(context.Context, *GetEnterpriseRequest) (*GetEnterpriseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEnterprise not implemented")
}
func (*UnimplementedEnterpriseServiceServer) UpdateEnterprise(context.Context, *UpdateEnterpriseRequest) (*UpdateEnterpriseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEnterprise not implemented")
}
func (*UnimplementedEnterpriseServiceServer) DeleteEnterprise(context.Context, *DeleteEnterpriseRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEnterprise not implemented")
}
func (*UnimplementedEnterpriseServiceServer) ListAllEnterprises(context.Context, *ListAllEnterprisesRequest) (*ListAllEnterprisesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAllEnterprises not implemented")
}

func RegisterEnterpriseServiceServer(s *grpc.Server, srv EnterpriseServiceServer) {
	s.RegisterService(&_EnterpriseService_serviceDesc, srv)
}

func _EnterpriseService_CreateEnterprise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEnterpriseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnterpriseServiceServer).CreateEnterprise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.EnterpriseService/CreateEnterprise",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnterpriseServiceServer).CreateEnterprise(ctx, req.(*CreateEnterpriseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnterpriseService_GetEnterprise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnterpriseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnterpriseServiceServer).GetEnterprise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.EnterpriseService/GetEnterprise",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnterpriseServiceServer).GetEnterprise(ctx, req.(*GetEnterpriseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnterpriseService_UpdateEnterprise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEnterpriseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnterpriseServiceServer).UpdateEnterprise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.EnterpriseService/UpdateEnterprise",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnterpriseServiceServer).UpdateEnterprise(ctx, req.(*UpdateEnterpriseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnterpriseService_DeleteEnterprise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEnterpriseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnterpriseServiceServer).DeleteEnterprise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.EnterpriseService/DeleteEnterprise",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnterpriseServiceServer).DeleteEnterprise(ctx, req.(*DeleteEnterpriseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnterpriseService_ListAllEnterprises_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAllEnterprisesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnterpriseServiceServer).ListAllEnterprises(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.EnterpriseService/ListAllEnterprises",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnterpriseServiceServer).ListAllEnterprises(ctx, req.(*ListAllEnterprisesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EnterpriseService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.EnterpriseService",
	HandlerType: (*EnterpriseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEnterprise",
			Handler:    _EnterpriseService_CreateEnterprise_Handler,
		},
		{
			MethodName: "GetEnterprise",
			Handler:    _EnterpriseService_GetEnterprise_Handler,
		},
		{
			MethodName: "UpdateEnterprise",
			Handler:    _EnterpriseService_UpdateEnterprise_Handler,
		},
		{
			MethodName: "DeleteEnterprise",
			Handler:    _EnterpriseService_DeleteEnterprise_Handler,
		},
		{
			MethodName: "ListAllEnterprises",
			Handler:    _EnterpriseService_ListAllEnterprises_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "enterprise.proto",
}
